function exportWebReference(outFile)
%EXPORTWEBREFERENCE  Dump parameters and complex responses for the web port.
%
%   EXPORTWEBREFERENCE(OUTFILE) writes a JSON file containing
%     - the default outer-ear and middle-ear parameter structs
%     - the child and otitis-media variants
%     - complex outer / middle / combined responses and middle-ear input
%       impedance on a shared log frequency grid, for several scenarios
%
%   The web app loads the PARAMETERS from this file so the two
%   implementations cannot drift apart by transcription, and its self-test
%   compares its own computation against the RESPONSES stored here.
%
%   Complex arrays are stored as separate .re and .im arrays because JSON
%   has no complex type.
%
%   See also MIDDLEEARRESPONSE, COMBINEDEARRESPONSE.

if nargin < 1
    outFile = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
                       'web', 'data', 'reference.json');
end

f = logspace(log10(20), log10(20000), 96).';

S = struct();
S.generated  = char(datetime('now','Format','yyyy-MM-dd HH:mm:ss'));
S.matlab     = version;
S.f          = f;

S.params = struct();
S.params.outer          = outerEarParams();
S.params.middle_normal  = middleEarParams();
S.params.middle_child   = middleEarParams('child');
S.params.middle_ome_mild     = middleEarParams('otitisMedia','mild');
S.params.middle_ome_moderate = middleEarParams('otitisMedia','moderate');
S.params.middle_ome_severe   = middleEarParams('otitisMedia','severe');

% ---- scenarios ---------------------------------------------------------
p1 = outerEarParams();

p1b = p1; p1b.canalModel = 'iec318'; p1b.canalLength = 0.030;
p1c = p1; p1c.azimuth = 45; p1c.elevation = 30; p1c.pinnaStrength = -0.4;

pn = middleEarParams();
pE1 = pn; pE1.L_te = pn.L_te*1.2;
pE2 = pn; pE2.C_is = pn.C_is*2;
pE3 = pn; pE3.R_te = pn.R_te*2;
pE4 = pn; pE4.C_cp = pn.C_cp*2;
pSh = pn; pSh.cavityPlacement = 'shunt';

cases = {
 'default',        p1,  pn
 'canal_iec318',   p1b, pn
 'pinna_oblique',  p1c, pn
 'E1_Lte_x1.2',    p1,  pE1
 'E2_Cis_x2',      p1,  pE2
 'E3_Rte_x2',      p1,  pE3
 'E4_Ccp_x2',      p1,  pE4
 'cavity_shunt',   p1,  pSh
 'child',          p1,  middleEarParams('child')
 'ome_mild',       p1,  middleEarParams('otitisMedia','mild')
 'ome_moderate',   p1,  middleEarParams('otitisMedia','moderate')
 'ome_severe',     p1,  middleEarParams('otitisMedia','severe')
};

S.cases = struct();
for k = 1:size(cases,1)
    name = cases{k,1};
    C = combinedEarResponse(cases{k,2}, cases{k,3}, f);
    e = struct();
    e.outerParams  = cases{k,2};
    e.middleParams = cases{k,3};
    e.outer    = cx(C.Houter);
    e.middle   = cx(C.Hmiddle);
    e.combined = cx(C.total);
    e.Zin      = cx(C.middle.inputImpedance);
    e.loadingRatio = C.loadingRatio;
    S.cases.(matlab.lang.makeValidName(name)) = e;
end

txt = jsonencode(S);
fid = fopen(outFile, 'w');
fwrite(fid, txt, 'char');
fclose(fid);
% Also write a .js wrapper so the page works when opened from disk (file://),
% where fetch() is blocked. Same content, different container.
jsFile = strrep(outFile, '.json', '.js');
fid = fopen(jsFile, 'w');
fwrite(fid, sprintf(['/* reference.js -- MATLAB-exported parameters and reference responses,\n' ...
    ' * wrapped as a global so the page works when opened directly from disk\n' ...
    ' * (file://) as well as over HTTP. Generated by exportWebReference.m;\n' ...
    ' * data/reference.json holds the same content for the offline jsc test. */\n' ...
    'window.__EAR_REFERENCE__ = ']), 'char');
fwrite(fid, txt, 'char');
fwrite(fid, sprintf(';\n'), 'char');
fclose(fid);

fprintf('wrote %s and %s (%.0f kB, %d cases, %d frequencies)\n', ...
        outFile, jsFile, numel(txt)/1024, size(cases,1), numel(f));

end

function s = cx(z)
s = struct('re', real(z(:)), 'im', imag(z(:)));
end
